### ISSUE TITLE
Moon plugins do not create generated directory tree properly

### ISSUE THREAD

**Issue by dmarszk** [MOonRails/MOONRAILS#3]
Test setup:
- Clean repository clone
- Eclipse Oxygen with workspace with both Demo and MOon projects imported
- JDK 1.8
- Run configuration attached

![image](https://user-images.githubusercontent.com/1038970/32846468-9b51961a-ca27-11e7-9f42-d5277b7c29b7.png)

The run fails (log attached)
[generationfail.txt](https://github.com/MOonRails/MOONRAILS/files/1475413/generationfail.txt)

It might be a mishap of my configuration - in that case having an instruction how to do it properly in README is much needed.

**Comment by dmarszk** [comment]
Setting working directory to Demo/src fixes the issue, but addressing it would improve intuitivity a lot.

**Comment by feiteira** [comment]
Good to know you found a workaround.
I'm currently working on processing the command line arguments for MOonRails and am refactoring parts of the folder structure. This wont be the final, but it should be a major step forward.

Part of the complaint is also that right now the Demo project contains the templates from the plugins.

The working branch for this patch is named command_line (23e515f21bdf8039a2f97d031fe07b7c818595e2)

**Comment by feiteira** [comment]
Can you check now with Maven?

`mvn install`
Go to target/Deployment
and type
`./moon Example`

**Comment by dmarszk** [comment]
After Maven downloaded the internet it all worked well. :)
